version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:10 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: echo "testing stuff" # run the `echo` command
      - run: npm run test
  hithere:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "helloo!!!"
workflows:
  version: 2.1
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere